# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

env:
  -TRAVIS_R_VERSION_STRING="3.5.0"

bioc_required: true
bioc_packages:
  - EBImage
  
# Needed to build EBImage from source
apt_packages:
  - libfftw3-dev

r_packages:
  - devtools

# Needed to use apt_packages
sudo: required

cache: packages

