# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

# Needed to use apt_packages
sudo: required

cache: packages

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
          - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"


bioc_required: true
bioc_packages:
  - EBImage

os:
  - linux

# Needed to build EBImage from source
apt_packages:
  - libcurl4-openssl-dev

r_packages:
  - devtools
  - covr
  - RcppTOML
  - fftwtools
