# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r


bioc_required: true
bioc_packages:
  - EBImage
  
# Needed to build EBImage from source
apt_packages:
  - libfftw3-dev

r_packages:
  - devtools
  - covr
  - RcppTOML
  - fftwtools

# Needed to use apt_packages
sudo: required

cache: packages

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
  - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - Rscript -e 'library("covr"); covr::codecov()'